/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Skript47 (https://sketchfab.com/Skript47)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-monitor-169-low-poly-game-ready-336de680dd9a4d84943d05d9c7dde1b0
Title: Computer Monitor 16:9 (Low Poly, Game Ready)
*/

import React, { useRef } from "react";
import { useGLTF, useVideoTexture } from "@react-three/drei";
import * as THREE from "three";

export default function Computer(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/computer.glb");
  const txt = useVideoTexture(
    props.texture ?? "/textures/projects/project1.mp4",
    {
      loop: true,
      muted: true,
      start: true,
    },
  );

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Monitor_01_A}
        />
        {/* Monitor */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={
            new THREE.MeshBasicMaterial({ map: txt, toneMapped: false })
          }
        >
          <meshBasicMaterial key={props.texture} map={txt} toneMapped={false} />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/computer.glb");
