/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Legado.Rural (https://sketchfab.com/Legado.Rural)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/el-buzon-de-las-palabras-39a32343979f4c62be4e754858dacf5e
Title: El Buzon de las Palabras
*/

import { useGLTF } from "@react-three/drei";

export default function Fancy(props) {
  const { nodes, materials } = useGLTF("/models/fancy.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <lineSegments
          geometry={nodes.Object_2.geometry}
          material={materials.Caja}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Caja}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Default_OBJ}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/fancy.glb");
